### ISSUE TITLE
CUDNN_STATUS_NOT_INITIALIZED on calling OpenPose Demo

### ISSUE THREAD

**Issue by luojeffery** [KyujinHan/Smplify-X-Perfect-Implementation#5]
Hello,
Upon running the Colab as-is without any changes, I encounter this error on the "Run Openpose on the extracted frames" cell. 
![image](https://github.com/user-attachments/assets/1b472816-6eb3-4955-890e-47473e1d180d)

I often see this issue for other OpenPose desktop users in [OpenPose's issue #1527](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1527) and some fix it by using -DUSE_CUDNN=OFF where the build openpose line would be, but that results in openpose not being properly compiled in Colab, and slows down OpenPose in general (according to others). So, I don't know what the fix is for Colab.
Thank you!

**Comment by KyujinHan** [comment]
Hello!
Thank you for your good insight.

I never seen before, so I don't know...
Did you use the `A100 GPU`?

![image](https://github.com/user-attachments/assets/c6bb769d-efe5-4a74-b357-3dc0a3a81588)
When I implement the Colab code with `A100 and L4 GPU`, there is no error.

Could you check your GPU in Colab??

Thank you!

**Comment by luojeffery** [comment]
Thank you, that worked! I was using T4 before, which didn't work well.
