### ISSUE TITLE
CUDNN_STATUS_VERSION_MISMATCH

### ISSUE THREAD

**Issue by PixelPantz** [KyujinHan/Smplify-X-Perfect-Implementation#7]
![Image](https://github.com/user-attachments/assets/507184b1-8f4b-4ef2-a83c-af733bf91ee2)

Hi! Thank you so much for your work. Google colab apparently changes versions of anything faster than I can test the project :(
I am using a100/l4.

**Comment by KyujinHan** [comment]
Hello! 
Could you tell me where the error is occurring?

Thank you!

**Comment by PixelPantz** [comment]
On installing openpose. In their repository, everyone complains about incompatibility with the new version of CUDA.

Thank you for helping.

**Comment by KyujinHan** [comment]
@PixelPantz   
Hello! Maybe, I fixed this error.  

I saw, the openpose cannot support cuda 12.5 currently. [Related to issue](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/2333).  

So, I added some code, which change the cuda version 12.5 to 12.2.  
When I tested, it is working now.  

Could you check the code?  
Thank you!

**Comment by PixelPantz** [comment]
Hello there! Yes, I've just checked and the code is working perfectly, thank you!
